### ISSUE TITLE
How do I transform this

### ISSUE THREAD

**Issue by waynetheisinger** [cloudinary/cloudinary_magento2#102]
We don't want to keep the media on the server so we need to remove all situations where the module falls back to the Magento media path.

How do I transform this

`$imageUrl = $helperImport->init($_product, 'product_base_image')->keepAspectRatio(true)->resize('300', '300')->getUrl();`

At the moment it produces:

`https://res-2.cloudinary.com/mowdirect/catalog/product/placeholder/default/image.gif`

but when the media folder is present it produces this

`https://res-5.cloudinary.com/mowdirect/image/upload/c_limit,dpr_2.0,f_auto,h_250,q_auto,w_300/v1/media/catalog/product/u/n/untitled_design_10_.png`

I'm guessing that the built in function uploads the image in order to transform it... when it isn't present locally how do I find the Cloudinary URL and then transform it?

**Comment by eyalktCloudinary** [comment]
Hey @waynetheisinger, thanks for reaching out!
I see that you've also created a ticket with us ([#158413](https://cloudinary.zendesk.com/agent/tickets/158413)). In any case, I'll answer here as well - 
In general, the way our module for Magento currently works, it is not possible to store the media **only** on Cloudinary. This means that media assets must reside both on Cloudinary and in the Magento server. 

To answer your question, the only way to retrieve the Cloudinary URLs of product images is by [setting up the API](https://cloudinary.com/documentation/magento_product_catalog_api#configuration), and using these endpoints -
GET - for a single SKU:
`https://{MAGENTO_HOST_OR_IP}/{MAGENTO_BASE_INSTALL_DIR}/rest/V1/cloudinary/products/{SKU}/media​`
POST - for multiple SKUs:
`https://{MAGENTO_HOST_OR_IP}/{MAGENTO_BASE_INSTALL_DIR}/rest/V1/cloudinary/products/media/get​`
(Include the desired SKUs in the request body, i.e - `{"skus": [sku1,sku2]}​`)
