### ISSUE TITLE
Transformations keep_frame is not working [bug]

### ISSUE THREAD

**Issue by emogerov** [cloudinary/cloudinary_magento2#105]
Hello,

I noticed a bug when compiling image urls in Plugin/Catalog/Block/Product/ImageFactory.php(I think it's the same for Model as well) plugin. 

At line 223 function createTransformation it checks if (isset($imageMiscParams['keep_frame'])) and then $this->keepFrame = ($imageMiscParams['keep_frame'] === 'frame') ? true : false;

private function createTransformation(array $imageMiscParams)

    $dimensions = $this->getDimensions($imageMiscParams);
    $transform = $this->configuration->getDefaultTransformation()->withDimensions($dimensions);

    if (isset($imageMiscParams['keep_frame'])) {
        $this->keepFrame = ($imageMiscParams['keep_frame'] === 'frame') ? true : false;
    }
    
    if ($this->keepFrame) {
        $transform->withCrop(Crop::lpad())
            ->withDimensions(Dimensions::squareMissingDimension($dimensions));
    } else {
        $transform->withCrop(Crop::limit());
    }

    return $transform;

However! in magento default settings "keep_frame" can only be true or false and not "frame", therefore => $this->keepFrame = false; which results in url being with c_limit rather than c_lpad:
https://res-3.cloudinary.com/dltuverpp/image/upload/c_limit,dpr_2.0,f_auto,h_260,q_auto,w_260/v1/media/catalog/product/1/_/1_26.jpg

Am I missing something. How to configure url to be with c_pad/c_lpad and is it safe to extended the file and override it with what I assume is the correct code line?

**Comment by emogerov** [comment]
Following $imageMiscParams it lead me to Magento_Catalog/Model/Product/Image/ParamsBuilder and on line 111 in overwriteDefaultValues function, 'keep_frame' => (bool) $frame. I can change it to string "frame" and then url output is correct with c_lpad and it's fixed but again my question is mostly 
1. Is it safe to override or am I approaching customizing transformation wrongly?
and
2. Is this known/intended or is it a bug?

**Comment by leptians** [comment]
@emogerov , apologies for the delay in responding you. we should release a fix for this and I would recommend for you to wait for this fix before making the changes yourself. thanks!
