### ISSUE TITLE
Validation on video url is not correct for Magento 2.4.X

### ISSUE THREAD

**Issue by DnD-Mimosa** [cloudinary/cloudinary_magento2#107]
Hi !

We found an issue on the validation used on the video page builder component. Since Magento 2.4, it's possible to specify a self hosted video url. The used rule is not validate-video-url but validate-video-source. However, you made an override of the ui component and used the old validation in your javascritp mixin.

Can you please now use validate-video-source and create your mixin with the good code ?
Files concerned in your extension:
https://github.com/cloudinary/cloudinary_magento2/blob/master/view/adminhtml/ui_component/pagebuilder_video_form.xml#L13
https://github.com/cloudinary/cloudinary_magento2/blob/master/view/adminhtml/web/js/form/element/validator-rules-mixin.js#L24
Files from core :
https://github.com/magento/magento2-page-builder/blob/develop/app/code/Magento/PageBuilder/view/adminhtml/ui_component/pagebuilder_video_form.xml#L80
https://github.com/magento/magento2-page-builder/blob/develop/app/code/Magento/PageBuilder/view/adminhtml/web/js/form/element/validator-rules-mixin.js#L202

Thank you very much !

Best Regards,
Florian.

**Comment by wissam-khalili** [comment]
Hi @DnD-Mimosa ,
Thank you for your input.
I would like to update you that a fix will be added to version 1.17 and I will update you once it will be released.
Regards,
Wissam

**Comment by wissam-khalili** [comment]
Hi @DnD-Mimosa ,

I would like to update you that the new version 1.17 was released.

Thanks,
Wissam
