### ISSUE TITLE
c_limit changed to c_pad

### ISSUE THREAD

**Issue by Seppo-Konttinen-Solteq** [cloudinary/cloudinary_magento2#124]
Somewhere along the way default way of getting product images with `c_limit` changed to `c_pad`.

Any possibility to get help how to control what is used? Is there configuration for that? Problem now is that `c_pad` resizes some of the images much smaller than `c_limit` probably because it's trying to maintain aspect ratio and some original images has somewhat non-standard ratio which in my opinion causes those to get really small.

Tried to alter settings:

Products Custom Transformation
Products Custom Transformation Behavior

with override behaviour but it just added `c_limit` to image url but left `c_pad` there also.

Thanks,
Seppo

**Comment by wissam-khalili** [comment]
Hi @Seppo-Konttinen-Solteq ,

Thanks for reaching out.

In order for me to investigate further, and find the root cause of the described issue, could you please share some additional information?

Which version of Magento do you have installed on your environment?
Which version of the Cloudinary module do you have installed on your environment?
Could you share a screenshot of the module's configurations page?
Was the issue just recently introduced? Or did you encounter it before as well?
Could you share a link to your Magento store's front site or a specific product page, so I could investigate further?
Do you have any additional 3rd party modules installed on your environment? If so, could you please provide a list of these plugins?
Would you be able to provide our dev team with access credentials to your server (SSH) so they could take a deeper look?
Any additional information would be greatly helpful.

Looking forward to your reply.

Best regards,
Wissam

**Comment by Seppo-Konttinen-Solteq** [comment]
Hi @wissam-khalili 

It can be reproduced with Magento Commerce 2.4.1 and 2.4.4-p2. I believe that the URL changed in version v1.19.0. We now use 1.19.2 which should be the latest.

Here is example url how it is now:

https://res.cloudinary.com/anora/image/upload/c_lpad,dpr_2.0,f_auto,h_700,q_auto,w_700/v1/own-brands/koskenkorva/products/koskenkorva-salmiakki-minttu-50cl-30vol.jpg

And before it was:

https://res.cloudinary.com/anora/image/upload/c_limit,dpr_2.0,f_auto,h_700,q_auto,w_700/v1/own-brands/koskenkorva/products/koskenkorva-salmiakki-minttu-50cl-30vol.jpg

So `c_limit` was changed to `c_lpad` which changed in version update without any actions on our side.

Here is the storefront https://nordicspirits.com/en/koskenkorva-salmiakki-minttu-liquorice-peppermint-shot-50-cl

Checked the code and there is this:

private function createTransformation(array $imageMiscParams)
    {
        $dimensions = $this->getDimensions($imageMiscParams);
        $transform = $this->configuration->getDefaultTransformation(true)->withDimensions($dimensions);

        if (isset($imageMiscParams['keep_frame'])) {
            $this->keepFrame = (bool) $imageMiscParams['keep_frame'];
        }

        if ($this->keepFrame) {
            $transform->withCrop(Crop::lpad())
                ->withDimensions(Dimensions::squareMissingDimension($dimensions));
        } else {
            $transform->withCrop(Crop::limit());
        }

        return $transform;
    }

I have not yet been able to dig deeper where the $this->keepFrame value is fetched.

**Comment by wissam-khalili** [comment]
Hi @Seppo-Konttinen-Solteq 

Here is a good explanation of how to fetch the “keep_frame“ attribute:

[Setting image keep frame to false in theme's view.xml does not work · Issue #4622 · magento/magento2](https://github.com/magento/magento2/issues/4622)

Could you have look?
Thanks

**Comment by wissam-khalili** [comment]
Hi @Seppo-Konttinen-Solteq ,

Any update on this issue?
Please let me know your feedback.

Regards,
Wissam

**Comment by wissam-khalili** [comment]
Hi @Seppo-Konttinen-Solteq ,

Have you got a chance to review my last comment?
Any findings on your side?

Regards,
Wissam

**Comment by Seppo-Konttinen-Solteq** [comment]
Actually checked that we don’t have any frame etting in view.xml. When checking https://devdocs.magento.com/guides/v2.3/frontend-dev-guide/themes/theme-images.html aspect_ratio and frame are true by default. And guessing that the bug fixed here https://github.com/magento/magento2/issues/4622 changed the way how it works?

--
Seppo Konttinen
Lead Developer

***@***.******@***.***>
+358 44 303 4070
solteq.com

S O L T E Q 



This email is from Solteq Plc and is intended only for the addressee. This email may contain privileged and confidential information. If you receive this email by mistake, please inform the sender about it and then delete it. Please do not produce, distribute or retain copies of this email. Thank you.



From: Seppo Konttinen ***@***.***>
Date: Tuesday, 15. November 2022 at 14.56
To: cloudinary/cloudinary_magento2 ***@***.***>, cloudinary/cloudinary_magento2 ***@***.***>
Cc: Mention ***@***.***>
Subject: Re: [cloudinary/cloudinary_magento2] c_limit changed to c_pad (Issue #124)
Hi.

Sorry being busy with other work. I was able to check the github issue comment quickly and I could test it out. But we havent’ touched to <frame> settings and figuring how c_limit changed to c_pad still or was there changes in Cloudinary module that made it happen now?

--
Seppo Konttinen
Lead Developer

***@***.******@***.***>
+358 44 303 4070
solteq.com

S O L T E Q 



This email is from Solteq Plc and is intended only for the addressee. This email may contain privileged and confidential information. If you receive this email by mistake, please inform the sender about it and then delete it. Please do not produce, distribute or retain copies of this email. Thank you.



From: wissam-khalili ***@***.***>
Date: Monday, 14. November 2022 at 11.45
To: cloudinary/cloudinary_magento2 ***@***.***>
Cc: Seppo Konttinen ***@***.***>, Mention ***@***.***>
Subject: Re: [cloudinary/cloudinary_magento2] c_limit changed to c_pad (Issue #124)

Hi @Seppo-Konttinen-Solteq<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSeppo-Konttinen-Solteq&data=05%7C01%7Cseppo.konttinen%40solteq.com%7C3198bd7f7cff4028fb8008dac62505f6%7C9e4eb25883584a33b3e9b734c884fc4b%7C0%7C0%7C638040159565592154%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QdGuELZ3KqX2m6ZpeccCWv7OHvP9Gn9F8PMa%2B0rdDZQ%3D&reserved=0> ,

Have you got a chance to review my last comment?
Any findings on your side?

Regards,
Wissam

**Comment by momoip** [comment]
Hi @Seppo-Konttinen-Solteq,

Would you confirm if using the boolean of aspect_ratio and the boolean of frame works for you?

Regards,
Mo

**Comment by wissam-khalili** [comment]
Hi @Seppo-Konttinen-Solteq ,

I am getting back to you about this issue.
Could you confirm if there were any changes in the XML files or in the Magento environment that caused this behavior?
Another essential point, we would like to understand is when this issue started.
Is it related to an upgrade of our Magento plugin?
If yes, could you please mention from which version to which version?

Thanks,
Wissam

**Comment by wissam-khalili** [comment]
To summarize this issue:

The default values for aspect_ratio and frame is true and in that case Cloudinary will use `l_pad`
This happened due to a new Magento version that changed the value of the keep frame.
**The solution:**
In order to change the default setting of the parent theme, the file located under ‘app/design/frontend/{Vendor}/{themename}/etc/view.xml’
(if the file isn’t there, there is a fallback to the parent theme)
For example:
```
         <image id="category_page_grid" type="small_image">
                <width>240</width>
                <height>300</height>
                <aspect_ratio>true</aspect_ratio>
                <frame>false</frame>
         </image>
```
Make sure to add those 2 lines :
```
<aspect_ratio>true</aspect_ratio>
<frame>false</frame>
```
