### ISSUE TITLE
iOS - Closing a fullscreen product video causes the browser to navigate back a page

### ISSUE THREAD

**Issue by embolden** [cloudinary/cloudinary_magento2#125]
Hello, I wanted to reach out to report a possible bug with the implementation of videos.

Steps to reproduce:
- Open homepage
- Navigate to a PDP with a video
- Play video
- Open fullscreen
- Close fullscreen

After closing the fullscreen video the page will navigate back to the previously loaded page.

This behavior has been observed on:
iPhone 12 Pro / iOS 16.1.1
iPhone Xs / iOS 15.6.1

Desktop browsers (Safari, Chrome, Firefox) and Android devices do have the same issue.

I noticed this while working on our dev/staging environments and to rule out any possibility of other modules being the issue I setup a clean install of Magento with the Luma theme and installed only the Cloudinary module.  The issue is still present on that installation.

Also, I wanted to mention that the core Vimeo implementation has changed: https://github.com/magento/magento2/commit/2b98dc6517c4148cb98afb25fa86efd63c348948, but these updates have not been reflected in the Cloudinary module yet.

Which version of Magento do you have installed on your environment?
  2.4.5-p1
Which version of the Cloudinary module do you have installed on your environment?
  Normal version: 1.18.0, Clean installation: 1.19.3
Could you share a screenshot of the module's configurations page?
<img width="1272" alt="settings" src="https://user-images.githubusercontent.com/1679978/210833841-959d2aaf-7b03-4c01-b893-261b2431fb58.png">
Was the issue just recently introduced? Or did you encounter it before as well?
  Issue was first noticed in December of 2021.  The version of Magento and the Cloudinary module were different then; but I don't know specific version numbers.
Could you share a link to your Magento store's front site or a specific product page, so I could investigate further?
  https://sab-stage.myscrubsandbeyond.com/grey-s-anatomy-spandex-stretch-v-neck-4-pocket-scrubs-tops.html?sab-allowed=1

Thanks,
Matt

**Comment by embolden** [comment]
@wissam-khalili Hi, has this been resolved?  I don't see an update to the module.

**Comment by embolden** [comment]
Yes, it does.

Magento 2.4.5-p1, Cloudinary 1.19.7.  Clean Magento install with no other extensions installed.  Viewing a cloudinary hosted video.

https://github.com/cloudinary/cloudinary_magento2/assets/1679978/cb5a2f51-65e7-4981-8e64-89500c8b64bc

**Comment by dannyv-cloudinary** [comment]
Hi @embolden. 

As far as I can see, this is actually an issue with Fotorama (the default video player in Magento), rather than Cloudinary. Could you please try again with a video not hosted by Cloudinary and let us know if you experience the same behaviour?

Thanks,
-Danny

**Comment by embolden** [comment]
Hi @dannyv-cloudinary ,

This does not happen with the Vimeo or YouTube players; only Cloudinary hosted video.

https://github.com/cloudinary/cloudinary_magento2/assets/1679978/eb99ea11-4152-4816-8cb5-84c4d06fbc4c

Thanks,
Matt

**Comment by embolden** [comment]
Dug deeper - looks like the issue might be in Webkit.  https://bugs.webkit.org/show_bug.cgi?id=227836
