### ISSUE TITLE
https://f.vimeocdn.com/js/froogaloop2.min.js is no longer available

### ISSUE THREAD

**Issue by asanka-atapattu** [cloudinary/cloudinary_magento2#126]
Hi

I am using cloudinary/cloudinary 1.19.3 and I am having an issue with the vimeo videos are not working on PDP image gallery area. 
In the browser console, there is an error 
`GET https://f.vimeocdn.com/js/froogaloop2.min.js net::ERR_ABORTED 403              fotorama-add-video-events.js:515 `  

The actual reason is https://f.vimeocdn.com/js/froogaloop2.min.js is no longer available.

Can this be fixed?

**Comment by wissam-khalili** [comment]
Hi @asanka-atapattu,

It seems that this Vimeo URL is not valid anymore.
Could you try to replace it with the following URL : 
https://f.vimeocdn.com/js_opt/froogaloop2.min.js 

Please let me know your feedback.
Thanks,
Wissam

**Comment by wissam-khalili** [comment]
Hi @asanka-atapattu,

Any feedback from my last comment?
If it still doesn't work, try the following :
Under [cloudinary_magento2](https://github.com/cloudinary/cloudinary_magento2) app Edit [view/frontend/web/js/fotorama-add-video-events.js](https://github.com/cloudinary/cloudinary_magento2/blob/6a87b14dd430708d7a7cb81804c3ac9927320ea7/view/frontend/web/js/fotorama-add-video-events.js) file and replace https://f.vimeocdn.com/js/froogaloop2.min.js with https://player.vimeo.com/api/player.js

Please let me know your feedback.

Regards,
Wissam,

**Comment by wissam-khalili** [comment]
Hi @asanka-atapattu,

I would like to update you that the fix was released.
Please upgrade to the new version 1.19.5.

Regards,
Wissam
