### ISSUE TITLE
Exception #0 (Exception): User Deprecated Functionality: Class is deprecated in /var/www/html/vendor/magento/framework/HTTP/ZendClient.php on line 27

### ISSUE THREAD

**Issue by dahua910** [cloudinary/cloudinary_magento2#127]
hi

I am using cloudinary/cloudinary 1.19.4 with magento 2.4.6 community.
Installation is fine, when I try to setup cloudinary account in magento 2 (stores --> configuration --> cloudinary)
I got this error:

any suggestion?

`1 exception(s):
Exception #0 (Exception): User Deprecated Functionality: Class is deprecated in /var/www/html/vendor/magento/framework/HTTP/ZendClient.php on line 27

Exception #0 (Exception): User Deprecated Functionality: Class is deprecated in /var/www/html/vendor/magento/framework/HTTP/ZendClient.php on line 27
<pre>#1 trigger_error() called at [vendor/magento/framework/HTTP/ZendClient.php:27]
#2 Magento\Framework\HTTP\ZendClient->__construct() called at [vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php:121]
#3 Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:108]
#4 Magento\Framework\ObjectManager\Factory\Compiled->create() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:150]
#5 Magento\Framework\ObjectManager\Factory\Compiled->get() called at [vendor/magento/framework/ObjectManager/Factory/Compiled.php:79]
#6 Magento\Framework\ObjectManager\Factory\Compiled->create() called at [vendor/magento/framework/ObjectManager/ObjectManager.php:56]
#7 Magento\Framework\ObjectManager\ObjectManager->create() called at [vendor/magento/module-config/Model/Config/BackendFactory.php:39]
#8 Magento\Config\Model\Config\BackendFactory->create() called at [vendor/magento/module-config/Model/Config/Structure/Element/Field.php:227]
#9 Magento\Config\Model\Config\Structure\Element\Field->getBackendModel() called at [vendor/magento/module-config/Block/System/Config/Form.php:424]
#10 Magento\Config\Block\System\Config\Form->getFieldData() called at [vendor/magento/module-config/Block/System/Config/Form.php:340]
#11 Magento\Config\Block\System\Config\Form->_initElement() called at [vendor/magento/module-config/Block/System/Config/Form.php:316]
#12 Magento\Config\Block\System\Config\Form->initFields() called at [vendor/magento/module-config/Block/System/Config/Form.php:256]
#13 Magento\Config\Block\System\Config\Form->_initGroup() called at [vendor/magento/module-config/Block/System/Config/Form.php:202]
#14 Magento\Config\Block\System\Config\Form->initForm() called at [vendor/magento/module-config/Block/System/Config/Form.php:542]
#15 Magento\Config\Block\System\Config\Form->_beforeToHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1094]
#16 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1099]
#17 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:660]
#18 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [vendor/magento/framework/View/Layout.php:578]
#19 Magento\Framework\View\Layout->_renderBlock() called at [vendor/magento/framework/View/Layout.php:555]
#20 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#21 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Element/AbstractBlock.php:507]
#22 Magento\Framework\View\Element\AbstractBlock->getChildHtml() called at [vendor/magento/module-config/view/adminhtml/templates/system/config/edit.phtml:32]
#23 include() called at [vendor/magento/framework/View/TemplateEngine/Php.php:71]
#24 Magento\Framework\View\TemplateEngine\Php->render() called at [vendor/magento/framework/View/Element/Template.php:263]
#25 Magento\Framework\View\Element\Template->fetchView() called at [vendor/magento/framework/View/Element/Template.php:293]
#26 Magento\Framework\View\Element\Template->_toHtml() called at [vendor/magento/module-backend/Block/Template.php:141]
#27 Magento\Backend\Block\Template->_toHtml() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1095]
#28 Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}() called at [vendor/magento/framework/View/Element/AbstractBlock.php:1099]
#29 Magento\Framework\View\Element\AbstractBlock->_loadCache() called at [vendor/magento/framework/View/Element/AbstractBlock.php:660]
#30 Magento\Framework\View\Element\AbstractBlock->toHtml() called at [vendor/magento/framework/View/Layout.php:578]
#31 Magento\Framework\View\Layout->_renderBlock() called at [vendor/magento/framework/View/Layout.php:555]
#32 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#33 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#34 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#35 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#36 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#37 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#38 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#39 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#40 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#41 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#42 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#43 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#44 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#45 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#46 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#47 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#48 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#49 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#50 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#51 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#52 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#53 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#54 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:606]
#55 Magento\Framework\View\Layout->_renderContainer() called at [vendor/magento/framework/View/Layout.php:557]
#56 Magento\Framework\View\Layout->renderNonCachedElement() called at [vendor/magento/framework/View/Layout.php:510]
#57 Magento\Framework\View\Layout->renderElement() called at [vendor/magento/framework/View/Layout.php:975]
#58 Magento\Framework\View\Layout->getOutput() called at [generated/code/Magento/Framework/View/Layout/Interceptor.php:41]
#59 Magento\Framework\View\Layout\Interceptor->getOutput() called at [vendor/magento/framework/View/Result/Page.php:260]
#60 Magento\Framework\View\Result\Page->render() called at [vendor/magento/framework/View/Result/Layout.php:171]
#61 Magento\Framework\View\Result\Layout->renderResult() called at [generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php:32]
#62 Magento\Backend\Model\View\Result\Page\Interceptor->renderResult() called at [vendor/magento/framework/App/Http.php:120]
#63 Magento\Framework\App\Http->launch() called at [vendor/magento/framework/App/Bootstrap.php:264]
#64 Magento\Framework\App\Bootstrap->run() called at [pub/index.php:30]
</pre>`

**Comment by wissam-khalili** [comment]
Hi @dahua910 ,

Thank you for your feedback.

* Could you kindly detail the steps you have taken in order to install the Cloudinary module?
* Could you share a screenshot of the module's configurations page?
* Do you have any additional 3rd party modules installed on your environment? If so, could you please provide a list of these plugins?
* 
Any additional information would be greatly helpful.

Looking forward to your reply.

Best regards,
Wissam

**Comment by wissam-khalili** [comment]
Hi @dahua910 ,

We have identified the issue.
This is caused by Magento 2.4.6 deprecated ZendFramework functionality.
We have released a fix in version 1.19.5.

Best Regards,
Wissam
