### ISSUE TITLE
Why queue processing download images locally?

### ISSUE THREAD

**Issue by allanmfx** [cloudinary/cloudinary_magento2#128]
I want to know why the actual image queue processing download Cloudinary images and store them locally if we just need the URL for showing the image?

I can see that all images from admin product thumbnail to all frontend variants point to Cloudinary URL so why images needs to be saved locally? This is a waste of resource.

**Comment by wissam-khalili** [comment]
Hi @allanmfx,

Thank you for reaching out.
Indeed, you are right.
For now, our Magento integration requires uploading the asset to the Magento account.
There is a plan to use the URL only without the storage to be implemented in the future.

Regards,
Wissam

**Comment by allanmfx** [comment]
Hi @wissam-khalili. I see you closed this issue as completed, is this issue fixed and implemented in the code base? If so, could you let me know which version this has been fixed? Thank you.

**Comment by wissam-khalili** [comment]
Hi @allanmfx,

As mentioned earlier, our Magento integration requires uploading the asset to the Magento account.
We are aware of this request to use the URL only without the storage but it is not planned for the near future.

Regards,
Wissam
