### ISSUE TITLE
Amazon S3 remote storage compatibility missing

### ISSUE THREAD

**Issue by manuel-inhertz** [cloudinary/cloudinary_magento2#129]
Hi, i can't get this integration to work with the remote storage on amazon S3 when this is enabled on magento.
Are you planning to integrate it?

**Comment by atdcloud** [comment]
@manuel-inhertz 
Can you please provide more details? Are you using another Magento plug-in that connects an S3 bucket to your Magento instance? Do you have a plug-in name?

**Comment by manuel-inhertz** [comment]
I'm using the core integration that is available in magento 2.4, i'm currently managing all my media assets in the remote bucket s3

**Comment by wissam-khalili** [comment]
Hi @manuel-inhertz,
The Magento plugin we have is to migrate the assets from Cloudinary to Magento, as described here :
https://cloudinary.com/documentation/magento_integration

We do not have a way to migrate assets from S3 directly.
Alternatively, you could upload the assets from S3 to Cloudinary and then to Magento.
Here is a guide:
https://cloudinary.com/documentation/upload_images#upload_from_a_private_storage_url

Regards,
Wissam
