### ISSUE TITLE
Upgrade cloudinary_php Dependency

### ISSUE THREAD

**Issue by dsh-mabel** [cloudinary/cloudinary_magento2#130]
The currently pinned versions of [cloudinary_php](https://github.com/cloudinary/cloudinary_php) (`"cloudinary/cloudinary_php": ">=2.7 <2.8.1"`) uses an outdated version of [guzzle_promise](https://github.com/guzzle/promises) that breaks when trying to access the Promise functions. It looks like the most current versions of the cloudinary_php library have updated to the static methods.

We cannot downgrade Guzzle for Magento either as we need the newer versions for _other_ modules. Is there a reason this Magento module is not using the newest `cloudinary_php` library?

**Comment by wissam-khalili** [comment]
Hi there,
Thank you for reaching out.
We have limited the Magento plugin to use cloudinary_php to version 2.8.
We do not upgrade it automatically.
We are considering updating the composer to support the latest version, but we would need to do some testing before that.

I will keep you posted on our proceedings.
Regards,
Wissam

**Comment by milindsingh** [comment]
The current version is breaking Magento 2.4.5 and above. Kindly prioritize this issue so that we are able to use cloudinary.

**Comment by dannyv-cloudinary** [comment]
Hi @milindsingh. Thanks for your comment. I will be sure to pass your feedback on to the development team

**Comment by kevpd** [comment]
Currently also working with Magento 2.4.5 and we are not able to use our admin configurations due to this version mismatch. When will the development team be able to implement this?

**Comment by wissam-khalili** [comment]
Hi there, this issue is planned to be fixed in our next version.
I will let you know once it will be released.
Thanks,
Wissam

**Comment by pauldonnelly** [comment]
Wissam, Any update on this?

Error: Call to undefined function GuzzleHttp\Promise\promise_for() in /vendor/cloudinary/cloudinary_php/src/Api/BaseApiClient.php:333

**Comment by Vdeub-cloudinary** [comment]
Hi @pauldonnelly, the team is planning to work on this issue this week.
We will update you accordingly.

**Comment by wissam-khalili** [comment]
Hi @pauldonnelly @milindsingh @kevpd @dsh-mabel ,

I would like to update you that we have released a new version 1.19.8 in our Git repo.

Please review and let me know your feedback.

Regards,
Wissam

**Comment by pauldonnelly** [comment]
Unfortunately it seems to be the same issue. The magento2 module upgraded to 1.19.8 and cloudinary_php upgraded to 2.10.2. If I look at the file I mentioned above, the promise_for() is still there. It should be GuzzleHttp\Promise\Create::promiseFor() as per the latest version of cloudinary_php. 

Im not sure why it hasnt updated to cloudinary_php version 2.11.0.

**Comment by wissam-khalili** [comment]
Hi @pauldonnelly,

Thank you for your feedback.
We will fix the issue early next week.
I will keep you updated once released.

Regards,
Wissam

**Comment by wissam-khalili** [comment]
Hi @pauldonnelly ,

I would like to update you that we have released a new version 1.19.90.
Please upgrade and let me know your feedback.

Regards,
Wissam

**Comment by pauldonnelly** [comment]
Thank you Wissam. I removed the module and pulled the new composer packages. Everything seems to work now.

**Comment by wissam-khalili** [comment]
Thank you for the update @pauldonnelly
