### ISSUE TITLE
Queue not processing videos

### ISSUE THREAD

**Issue by davidtay** [cloudinary/cloudinary_magento2#131]
https://github.com/cloudinary/cloudinary_magento2/blame/a48b325aa0a8c3b805cf171b1a1cbcbcb7ea924b/Model/Configuration.php#L704

The Cloudname is null by default, so all videos are replaced with image.

**Comment by wissam-khalili** [comment]
Hi @davidtay ,

Please note that we have fixed this issue in our last version which was released 3 weeks ago.
Please give it a try.

Regards,
Wissam
