### ISSUE TITLE
Interface changes

### ISSUE THREAD

**Issue by janbiesiada** [cloudinary/cloudinary_magento2#132]
in magento 2.4.7 there are interface changes that introduces stronger output type and it gives example error:

Fatal error: Declaration of Cloudinary\Cloudinary\Model\Logger\OutputLogger::getVerbosity() must be compatible with Symfony\Component\Console\Output\OutputInterface::getVerbosity(): int in /var/www/html/vendor/cloudinary/cloudinary-magento2/Model/Logger/OutputLogger.php on line 105

https://github.com/cloudinary/cloudinary_magento2/blob/cd520d2386a9c06f2572a47cd549133610c45663/Model/Logger/OutputLogger.php#L95

**Comment by wissam-khalili** [comment]
Hi @janbiesiada,

Thank you for your input.

This issue is under investigation and we will fix it in our next version.

Best Regards,
Wissam

**Comment by wissam-khalili** [comment]
Hi @janbiesiada .

I would like to update you that we have released a new version that fixes the issue.
It is version 1.20.0.
 
Can you please upgrade the Cloudinary plugin to this new version and let me know your feedback?
 
Best Regards,
Wissam
