### ISSUE TITLE
Install via Composer doesn't works

### ISSUE THREAD

**Issue by osrecio** [cloudinary/cloudinary_magento2#2]
The package: cloudinary/magento2-module-cloudinary doesn't exists in packagist. 

https://packagist.org/?query=cloudinary%2Fmagento2-module-cloudinary

I get an error from command line:
```
$composer require cloudinary/magento2-module-cloudinary                                                                                        

  [InvalidArgumentException]
  Could not find a matching version of package cloudinary/magento2-module-cloudinary. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).
```

Could you add it to packagist?

**Comment by idobarnoam** [comment]
Hi @osrecio 

Currently, a composer installation is indeed not available.

There is a request with our dev team to also allow a composer install and it's in the works.

I would be happy to update this thread once there are any insights regarding this.

**Comment by osrecio** [comment]
Thanks for your reply

**Comment by idobarnoam** [comment]
@osrecio Just wanted to update the [composer installation](https://github.com/cloudinary/cloudinary_magento2#-install-via-composer) was recently made available.
