### ISSUE TITLE
Should be excluded from sitemaps!

### ISSUE THREAD

**Issue by IbrahimS2** [cloudinary/cloudinary_magento2#23]
Why Cloudinary changing the URLs in the image sitemaps?

![image](https://user-images.githubusercontent.com/19901858/56080221-a99d8c00-5e06-11e9-9969-2a5e5e82550e.png)

**Comment by idobarnoam** [comment]
@MageSuper we use links to deliver images and transformed images. That is why they are changed.
Is that what you are referring to?

**Comment by eyalktCloudinary** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com, or create a new ticket if you have any additional issues.
