### ISSUE TITLE
Cloudinary 1.9.0 incompatible with Magento Open Source 2.2.8

### ISSUE THREAD

**Issue by kevinvarley** [cloudinary/cloudinary_magento2#28]
If you install Cloudinary 1.9.0 on Magento Open Source 2.2.8 and then run di:compile you will be greeted with the following error

`Fatal error: Interface 'Magento\Framework\App\Action\HttpPostActionInterface' not found in /var/www/html/vendor/cloudinary/cloudinary-magento2/Controller/Adminhtml/Ajax/RetrieveImage.php on line 25`

The file in question exists in Magento 2.3.0:

https://github.com/magento/magento2/blob/2.3.0/lib/internal/Magento/Framework/App/Action/HttpPostActionInterface.php

But does not in 2.2.8:

https://github.com/magento/magento2/blob/2.2.8/lib/internal/Magento/Framework/App/Action/HttpPostActionInterface.php

Is it possible to produce a compatability fix for this? Or update your composer.json to require a particular Magento version?

Thanks

**Comment by idobarnoam** [comment]
@kevinvarley thanks for bringing this to our attention.

We have a request with our dev team to look into this. We will update here with any new insights.

**Comment by kevinvarley** [comment]
Thanks @idobarnoam , appreciated!

**Comment by eyalktCloudinary** [comment]
Closing due to time elapsed. Seems to be fixed.
