### ISSUE TITLE
M2.3.1 cannot use WYSIWYG image upload.

### ISSUE THREAD

**Issue by pauldonnelly** [cloudinary/cloudinary_magento2#29]
I've installed your M2 module using Magento 2.3.1 and immediately the WYSIWYG editor throws an error when you click the image icon. Error below.
As soon as I disable Cloudinary it works again.
Need a solution as soon as possible as it's a Live website.

`[30-May-2019 09:16:56 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getIsResizeEnabled() on null in public_html/vendor/magento/module-cms/view/adminhtml/templates/browser/content/uploader.phtml:20
Stack trace:
#0 public_html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include()
#1 public_html/vendor/magento/framework/View/Element/Template.php(271): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Cms\Block\Adminhtml\Wysiwyg\Images\Content\Uploader\Interceptor), '/home/mullanlig...', Array)
#2 public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Element\Template->fetchView('/home/mullanlig...')
#3 public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Cms\Block\Adminhtml\Wysiwyg\Images\Content\Uploader\Interceptor->___callParent('fetchView', Array)
#4 public_html/vendor/magento/framework/Interc in public_html/vendor/magento/module-cms/view/adminhtml/templates/browser/content/uploader.phtml on line 20`

**Comment by idobarnoam** [comment]
@pauldonnelly  thanks for pointing this out.

Kindly let us take this internally and see how to approach this.

**Comment by aandrade1234** [comment]
@pauldonnelly / @idobarnoam  any workaround for this issue ?
I found this issue on magento 2 that can help -> https://github.com/magento/magento2/issues/22394

**Comment by pini-girit** [comment]
Fixed on v1.9.1
