### ISSUE TITLE
Sync catalog from cloudinary back to Magento

### ISSUE THREAD

**Issue by azngeek** [cloudinary/cloudinary_magento2#56]
Hello,

i have tons of product images on my cloudinary account. Is it possible to refer to that images by inserting some data in some tables? I need the required relations in the tables to do that but could not find any information in the documentation.

**Comment by leptians** [comment]
Hi, can you elaborate more on what tables are you referring to? Are you referring to the tables inside Magento DB?
If you are trying to migrate your product images for your Magento environment, you can refer to the following [article](https://support.cloudinary.com/hc/en-us/articles/203152461-How-to-setup-Cloudinary-s-Magento-module-) for migration.

**Comment by eyalktCloudinary** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com, or create a new ticket if you have any additional issues.
