### ISSUE TITLE
"Unsupported Zip File" error when uploading link to Downloadable Product

### ISSUE THREAD

**Issue by peterjaap** [cloudinary/cloudinary_magento2#57]
I want to create a downloadable product in my Magento 2 installation. I can do that here;

![image](https://user-images.githubusercontent.com/431360/76624210-2a906680-6535-11ea-818f-38f5ef691b6b.png)

But when I try to upload a Zip file, I get a warning "Unsupported Zip File".

![image](https://user-images.githubusercontent.com/431360/76624304-527fca00-6535-11ea-88bb-3f4631b67c6d.png)

It turns out, your extension also triggers when uploading a file for a downloadable product and complains its not an image.

Solution; Cloudinary upload should not be used/triggered when uploading a file to Downloadable Products.

**Comment by eyalktCloudinary** [comment]
@peterjaap Thanks for reporting! We're currently investigating the described behavior, and we'll update you about any insight we have.

**Comment by pniel-cohen** [comment]
Hi,
Please try upgrading to the latest version, should be OK now.
Thanks!

**Comment by billalyasir** [comment]
> Hi, Please try upgrading to the latest version, should be OK now. Thanks!

Broh, I got this similar problem with nodejs, images are correctly uploading but when i try to upload zip file, it showing error on my console : { message: 'Unsupported ZIP file', name: 'Error', http_code: 400 } 

Here is my code: 

`const Order = require("../../models/Order/Order");
const asyncHandler = require("express-async-handler");
const cloudinary = require("../../utils/cloudinary");

const createOrder = asyncHandler(async (req, res) => {
  try {
    let files = [...req.body.files];
    let filesBuffers = [];

    for (let i = 0; i < files.length; i++) {
      const result = await cloudinary.uploader.upload(files[i], {
        folder: "orders",
        resource_type: "auto",
      });
      filesBuffers.push({
        public_id: result.public_id,
        image: result.secure_url,
      });
      console.log(result);
    }
    req.body.files = filesBuffers;
    const service = await Order.create(req.body);
    res.json(service);
  } catch (error) {
    console.log(error);
  }
});

module.exports = { createOrder };
`
