### ISSUE TITLE
Cannot upload any file using \Magento\MediaStorage\Model\File\Uploader

### ISSUE THREAD

**Issue by maxacarvalho** [cloudinary/cloudinary_magento2#58]
Hello,

My Magento version is 2.3.4 and I'm using an extension that uploads customer reviews from a CSV file.

The problem happens when trying to upload the CSV file, an exception is being thrown by the class `Cloudinary\Cloudinary\Core\CloudinaryImageProvider` method `upload()`.

Apparently the Cloudinary's extension is overriding everything that's related to `\Magento\MediaStorage\Model\File\Uploader`.

Although I love using Cloudinary's service I should be able to use the other Magento's features. For example, here I'm simply trying to upload a CSV file that will be processed and can probably be removed after, so I don't need to upload that to Cloudinary.

Help needed!

Thanks.

**Comment by eyalktCloudinary** [comment]
Hey @maxacarvalho, thanks for reaching out! We're working on a fix that should be available soon with our next release.

**Comment by pniel-cohen** [comment]
Hi,
Please try upgrading to the latest version, it should be OK now.
Thanks!
