### ISSUE TITLE
Improper error message

### ISSUE THREAD

**Issue by chelevich** [cloudinary/cloudinary_magento2#72]
https://github.com/cloudinary/cloudinary_magento2/blob/b3ec3cec487286403d7474ee88c0fc56486554f7/Model/BatchDownloader.php#L29

The error message says command is `cloudinary:download:stop`
Actually the command is `cloudinary:migration:stop`

**Comment by pniel-cohen** [comment]
Should be OK now, thanks for letting us know :)

**Comment by chelevich** [comment]
There's a similar error message fixed in the latest release in another file.
BatchDownloader.php still has the issue

**Comment by pniel-cohen** [comment]
Fixed on v1.14.2, should be released soon.
Thanks!
