### ISSUE TITLE
Swatch Attribute Image Handler isn't been overwritten

### ISSUE THREAD

**Issue by aandrade1234** [cloudinary/cloudinary_magento2#79]
The function getSwatchMediaUrl() on Magento\Swatches\Helper\Media class isn't returning Cloudinary URL.

**Comment by eyalktCloudinary** [comment]
@aandrade1234 Thanks for reaching out! 
Currently, the extension does not affect product swatches. This is by design.
The URLs are being generated during the Front-End rendering.
