### ISSUE TITLE
Issue with Magento 2.4 setup:install with system configuration in config.php

### ISSUE THREAD

**Issue by rrojin-mcfadyen** [cloudinary/cloudinary_magento2#87]
An issue with Magento 2.4 setup: install command when having system configuration in config.php

![Screenshot from 2021-03-22 23-05-13](https://user-images.githubusercontent.com/75588464/112033136-209b3d80-8b63-11eb-9098-ff173a6f8708.png)

Step to reproduce:
Run `bin/magento setup: install` with some configuration in config.php on a fresh database and without env.php

`bin/magento setup:install -vvv --db-host="mysql_che" --db-password="root" --db-user="root" --db-name="new" --admin-firstname="admin" --admin-lastname="admin" --elasticsearch-host="elastic_che" --elasticsearch-port="9200" --admin-user="admin" --admin-password="admin123" --admin-email="admin@example.com" --cleanup-database`

**Comment by eyalktCloudinary** [comment]
Fixed on v1.14.8 - Closing issue.
